// frontend/src/components/layout/Header.vue
<script setup lang="ts">
import { computed } from 'vue'
import { useAuthStore } from '@/stores/auth'
import { useRouter } from 'vue-router'

const authStore = useAuthStore()
const router = useRouter()

const userName = computed(() => authStore.user?.chineseName || authStore.user?.username || '用户')
const userInitial = computed(() => userName.value.charAt(0))

const handleLogout = async () => {
  authStore.logout()
  router.push('/login')
}
</script>

<template>
  <header class="sticky top-0 z-50 border-b border-white/10 backdrop-blur-md bg-slate-900/50">
    <div class="flex h-16 items-center justify-between px-6">
      <div class="flex items-center gap-3">
        <h1 class="text-xl font-bold text-white">
          彼得扶运营中心
        </h1>
      </div>

      <div class="relative">
        <button
          class="flex items-center gap-3 rounded-lg px-3 py-2 transition-colors hover:bg-white/10"
          @click="handleLogout"
        >
          <div class="flex h-8 w-8 items-center justify-center rounded-full bg-gradient-to-br from-blue-500 to-purple-500 text-white font-medium">
            {{ userInitial }}
          </div>
          <span class="text-sm font-medium text-white/90">{{ userName }}</span>
          <i class="fas fa-sign-out-alt text-xs text-white/50" />
        </button>
      </div>
    </div>
  </header>
</template>

// frontend-next/src/components/layout/header.tsx
'use client'

import { useAuthStore } from '@/stores/auth-store'
import { Button } from '@/components/ui/button'
import { LogOut, User, Menu } from 'lucide-react'
import Link from 'next/link'
import { useRouter } from 'next/navigation'

export function Header() {
  const { user, logout } = useAuthStore()
  const router = useRouter()

  const handleLogout = () => {
    logout()
    router.push('/login')
  }

  return (
    <header className="fixed right-0 top-0 z-30 h-16 border-b border-white/10 bg-black/20 backdrop-blur-xl">
      <div className="flex h-full items-center justify-end gap-4 px-6">
        {user ? (
          <>
            <div className="flex items-center gap-2 text-sm text-white/80">
              <User className="h-4 w-4" />
              <span>{user.username}</span>
              {user.role === 'admin' && (
                <span className="rounded bg-indigo-500/30 px-2 py-0.5 text-xs text-indigo-300">
                  管理员
                </span>
              )}
            </div>
            <Button variant="ghost" size="sm" onClick={handleLogout}>
              <LogOut className="h-4 w-4" />
              <span>登出</span>
            </Button>
          </>
        ) : (
          <Link href="/login">
            <Button variant="secondary" size="sm">
              登录
            </Button>
          </Link>
        )}
      </div>
    </header>
  )
}
